AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager for Teddy AI Service'

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: teddy-ai
  
  Environment:
    Type: String
    Description: Environment name
    AllowedValues: [dev, stage, prod]
    Default: dev

Resources:
  # Application Secrets
  ApplicationSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Environment}-${ProjectName}-secrets'
      Description: !Sub 'Application secrets for ${ProjectName} ${Environment} environment'
      SecretString: !Sub |
        {
          "DATABASE_URL": "postgresql://teddy_user:changeme@localhost:5432/teddy_ai?options=-csearch_path%3Dteddy_ai",
          "DATABASE_SCHEMA": "teddy_ai",
          "REDIS_URL": "",
          "OPENAI_API_KEY": "your-openai-api-key-here",
          "ANTHROPIC_API_KEY": "",
          "GOOGLE_API_KEY": "",
          "SNOWFLAKE_ACCOUNT": "JJODRXK-FP74384",
          "SNOWFLAKE_USER": "BIRDDOG_GEOVIEWER",
          "SNOWFLAKE_PASSWORD": "your-snowflake-password-here",
          "SNOWFLAKE_DATABASE": "BIRDDOG_DATA",
          "SNOWFLAKE_SCHEMA": "CURATED",
          "SNOWFLAKE_WAREHOUSE": "BIRDDOG_WH",
          "SNOWFLAKE_ROLE": "DATAENGINEERINGADMIN",
          "JWT_SECRET_KEY": "your-jwt-secret-key-here",
          "JWT_ALGORITHM": "HS256",
          "ENABLE_AUTHENTICATION": "false",
          "DEBUG": "false"
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ApplicationSecretsArn:
    Description: Application Secrets ARN
    Value: !Ref ApplicationSecrets
    Export:
      Name: !Sub '${Environment}-${ProjectName}-secrets-arn'
  
  ApplicationSecretsName:
    Description: Application Secrets Name
    Value: !Sub '${Environment}-${ProjectName}-secrets'
    Export:
      Name: !Sub '${Environment}-${ProjectName}-secrets-name'
