AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager exports for existing Teddy AI Service secrets'

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: teddy-ai
  
  Environment:
    Type: String
    Description: Environment name
    AllowedValues: [dev, stage, prod]
    Default: dev

Resources:
  # This is a dummy resource to make CloudFormation happy
  # We're just creating exports for the existing secret
  DummyWaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  ApplicationSecretsArn:
    Description: Application Secrets ARN
    Value: 'arn:aws:secretsmanager:us-east-1:551565094761:secret:dev-teddy-ai-secrets-PBJ87M'
    Export:
      Name: !Sub '${Environment}-${ProjectName}-secrets-arn'
  
  ApplicationSecretsName:
    Description: Application Secrets Name
    Value: !Sub '${Environment}-${ProjectName}-secrets'
    Export:
      Name: !Sub '${Environment}-${ProjectName}-secrets-name'
